#
# Basic version of stack, for Github
#
version: "3.3"
services:
  # An instance of RedPanda Schema Registry
  # To run it as a standalone container:
  #   docker network create redpanda-network
  #   docker volume create redpanda-volume
  #   docker run --name=schema_registry --net=redpanda-network -v "redpanda-volume:/var/lib/redpanda/data" -p 8081:8081 \
  #     docker.vectorized.io/vectorized/redpanda start --overprovisioned --smp 1 --memory 250M
  schema_registry:
    image: docker.vectorized.io/vectorized/redpanda
    networks:
      - redpanda-network
    ports:
      - "8081:8081"
    command:
      - start
      - --overprovisioned
      - --smp 1
      - --memory 250M

  example1-rabbitmq:
    image: rabbitmq:3-management
    container_name: example1-rabbitmq
    hostname: example1-rabbitmq
    ports:
      - "5672:5672"
      - "8080:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: development
    volumes:
      - ./rabbitmq_setup.sh:/scripts/rabbitmq_setup.sh:ro


volumes:
  redpanda-volume:
  rabbitmq-volume:

networks:
  external:
  redpanda-network:
